site_name: InDelsTopo
site_url: https://github.com/USF-DNA-Knot-Math/InDelsTopo/

repo_url: https://github.com/USF-DNA-Knot-Math/InDelsTopo/
repo_name: USF-DNA-Knot-Math/InDelsTopo

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - yaml

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv     # Cross-reference to Python stdlib
          options:
            docstring_style: numpy                     # Support "Attributes" and "Internal Attributes"
            show_source: false                         # Hide source code blocks
            show_signature: true                       # Show function/method signatures
            show_if_no_docstring: false                # Skip undocumented members
            show_root_toc_entry: false                 # Don’t repeat module name
            merge_init_into_class: true                # Merge __init__ doc into class doc
            members_order: source                      # Keep definition order
            inherited_members: false                   # Hide inherited methods
            filters:                                   # Hide unwanted or private members
              - "!^_"
              - "!^__version__$"
              - "!^__all__$"
              - "!^__author__$"
              - "!^__email__$"

nav:
  - Home: index.md
  - API Reference: reference.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/USF-DNA-Knot-Math/InDelsTopo
