site_name: InDelsTopo
site_url: https://github.com/USF-DNA-Knot-Math/InDelsTopo/

repo_url: https://github.com/USF-DNA-Knot-Math/InDelsTopo/
repo_name: USF-DNA-Knot-Math/InDelsTopo

theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - header.autohide
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    - palette.toggle
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv   # Link to Python stdlib
          options:
            docstring_style: numpy                   # Recognize Attributes/Internal Attributes
            show_source: false                       # Hide source code
            show_signature: true                     # Show function signatures
            show_if_no_docstring: false
            show_root_toc_entry: false
            merge_init_into_class: true
            members_order: source
            inherited_members: false
            filters:
              - "!^_"
              - "!^__version__$"
              - "!^__all__$"
              - "!^__author__$"
              - "!^__email__$"

nav:
  - Home: index.md
  - API Reference: reference.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/USF-DNA-Knot-Math/InDelsTopo
  generator: false

copyright: >
  © 2025 USF DNA-Knot Math Group — Documentation built with
  <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">Material for MkDocs</a>.
